# Generated by Django 5.2.8 on 2025-11-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_ID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=30)),
                ('mfc_date', models.CharField(max_length=10)),
                ('seller_ID', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=10)),
            ],
        ),
    ]
