# Generated by Django 5.2.8 on 2025-11-22 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_ID',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='seller_ID',
            new_name='seller_id',
        ),
    ]
